package com.st.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.ws.client.core.WebServiceTemplate;

import com.st.dto.schemas.Login;
import com.st.dto.schemas.LoginResponse;
import com.st.dto.schemas.ObjectFactory;
import com.st.service.ILoginWs;

@Service
public class LoginWsServiceImpl implements ILoginWs {

	@Autowired
	private WebServiceTemplate webServiceTemplate;

	// this Object is generated by maven plugin so it cannot be inyected
	private ObjectFactory objectFactory = new ObjectFactory();

	private static final String USER_NAME = "USER_NAME";
	private static final String PASSWORD = "PASSWORD";

	@Override
	public LoginResponse doLogin() {
		Login login = objectFactory.createLogin();
		login.setUsername(System.getenv(USER_NAME));
		login.setPassword(System.getenv(PASSWORD));
		return (LoginResponse) webServiceTemplate.marshalSendAndReceive(login);
	}

}
